name: rekap_keuangan
description: A new Flutter project.

version: 1.0.7+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cached_network_image: ^1.1.3
  path_provider: ^1.6.11
  sqflite: ^1.3.0
  shared_preferences: 0.5.7+3  
  rxdart: ^0.24.0
  dio: ^1.0.14
  flutter_bloc: ^6.0.1
  intl: ^0.16.1
  intro_slider: ^2.2.9
  font_awesome_flutter: ^8.8.1
  flutter_iconpicker: ^1.1.2
  flutter_material_color_picker: ^1.0.5  
  progress_dialog: ^1.2.2
  equatable: ^1.1.1   
  flutter_launcher_icons: ^0.7.5 
  firebase_admob: ^0.10.0+2
  fluttertoast: ^4.0.1
  share: ^0.6.4+3
  image_picker: ^0.6.7+2
  path: ^1.6.4
  charts_flutter: ^0.9.0
  month_picker_dialog: ^0.3.2
  flutter_masked_text: ^0.8.0
  flutter_native_admob: ^2.1.0
  permission_handler: ^5.0.1+1
  ext_storage: 1.0.3
  package_info: ^0.4.0+16  
  store_redirect: 1.0.2  
  url_launcher: ^5.5.3
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1 
  rflutter_alert: ^1.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  

flutter_icons:
  image_path: "assets/icons/icon_launcher.png"
  android: "icon_launcher"
  